version: '3.7'

services:
  database_ignite:
    image: postgres
    container_name: rentx_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=rentx
      - POSTGRES_PASSWORD=rentx
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentx_app
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
      - rentx_node_modules:/usr/app/node_modules
    working_dir: /usr/app
    command: sh -c "npm install && npm run start"

volumes:
  rentx_node_modules:
  pgdata:
