version: '3.7'

services:
  app:
    build: .
    container_name: rentx
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
      - rentx_node_modules:/usr/app/node_modules
    working_dir: /usr/app
    command: sh -c "npm install && npm run start"

volumes:
  rentx_node_modules:
